#!/usr/bin/env python3
"""Apply a zabbly extraction (INCUS_TAG) and a patch manifest (from
fetch_patches.py) to incus.spec: bump Version: and (re)write a marked block of
Patch: lines. %prep already uses %autosetup -p1, so no %prep edits are needed
-- declaring Patch: lines is enough for them to get applied automatically.

Also optionally prepends a changelog entry to incus.changes.

Safe to re-run: the Patch: block is delimited by marker comments and fully
replaced on each run, so regenerating after zabbly rebases its cherry-pick
list just needs extract_zabbly.py + fetch_patches.py + this script run again.
"""
import argparse
import json
import re
import sys
import time
from pathlib import Path

PATCH_BLOCK_START = "# --- zabbly cherry-pick patches (auto-generated by update_spec.py, do not edit by hand) ---"
PATCH_BLOCK_END = "# --- end zabbly cherry-pick patches ---"


def strip_v(tag):
    return tag[1:] if tag.startswith("v") else tag


def update_version(spec, version):
    new_spec, n = re.subn(
        r'^(Version:\s+)\S+', lambda m: m.group(1) + version, spec, count=1, flags=re.M
    )
    if n == 0:
        sys.exit("error: no Version: line found in spec")
    return new_spec


def ensure_v_prefixed_source(spec):
    """linuxcontainers.org only reliably keeps a v-prefixed release tarball
    URL around long-term -- the plain "%{name}-%{version}.tar.xz" name has
    been observed to 404 even for a previously-working version once a newer
    release comes out (v6.0.6/v7.0.1 still had it at the time this was
    written, v7.2.0 and v7.3.0 did not). Force the Source:/Source1: URLs and
    local filenames to the v-prefixed form so this doesn't silently break."""
    pattern = re.compile(r'^(Source1?:\s+\S*/%\{name\}-)(?:v)?(%\{version\}\.tar\.xz(?:\.asc)?)$', re.M)
    return pattern.sub(r'\g<1>v\g<2>', spec)


def build_patch_block(manifest):
    lines = [PATCH_BLOCK_START]
    for p in manifest:
        tag = f"Patch{p['number']}:"
        lines.append(f"{tag:<16}{p['file']}")
    lines.append(PATCH_BLOCK_END)
    return "\n".join(lines)


def insert_or_replace_patch_block(spec, block):
    pattern = re.compile(re.escape(PATCH_BLOCK_START) + r'.*?' + re.escape(PATCH_BLOCK_END), re.S)
    if pattern.search(spec):
        return pattern.sub(block, spec)

    lines = spec.splitlines()
    last_source_idx = None
    for i, line in enumerate(lines):
        if re.match(r'^Source\d*:', line):
            last_source_idx = i
    if last_source_idx is None:
        sys.exit("error: no Source: line found to anchor the patch block")
    lines.insert(last_source_idx + 1, "")
    lines.insert(last_source_idx + 2, block)
    return "\n".join(lines) + "\n"


def prepend_changelog(changes_path, version, tag, author, patch_count):
    ts = time.strftime("%a %b %d %H:%M:%S UTC %Y", time.gmtime())
    entry = "\n".join([
        "-" * 67,
        f"{ts} - {author}",
        "",
        f"- Update to Incus {version} (zabbly {tag}, {patch_count} cherry-picked fixes).",
        "",
    ])
    old = changes_path.read_text() if changes_path.exists() else ""
    changes_path.write_text(entry + old)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--extract", required=True, help="JSON from extract_zabbly.py")
    ap.add_argument("--manifest", required=True, help="manifest.json from fetch_patches.py")
    ap.add_argument("--changes", help="Path to .changes file to prepend an entry to")
    ap.add_argument("--author", help='e.g. "Jane Doe <jane@example.com>"; required if --changes is given')
    args = ap.parse_args()

    if args.changes and not args.author:
        sys.exit("error: --author is required when --changes is given")

    spec_path = Path(args.spec)
    extract_data = json.loads(Path(args.extract).read_text())
    manifest = json.loads(Path(args.manifest).read_text())

    version = strip_v(extract_data["tag"])
    spec = spec_path.read_text()
    spec = update_version(spec, version)
    spec = ensure_v_prefixed_source(spec)
    spec = insert_or_replace_patch_block(spec, build_patch_block(manifest))
    spec_path.write_text(spec)
    print(f"updated {spec_path}: Version -> {version}, {len(manifest)} Patch entries", file=sys.stderr)

    if args.changes:
        prepend_changelog(Path(args.changes), version, extract_data["tag"], args.author, len(manifest))
        print(f"prepended changelog entry to {args.changes}", file=sys.stderr)


if __name__ == "__main__":
    main()
